In [3]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Understanding Data

In [4]:
df = pd.read_csv('vehicles.csv')

## 1.Asking Basic Questions

    1.How big is the Data ?

In [5]:
df.shape

(426880, 26)

    2.How does the data look like ?

In [6]:
df.sample(50)

,id,url,region,region_url,price,year,manufacturer,model,condition,cylinders,...,size,type,paint_color,image_url,description,county,state,lat,long,posting_date
188618,7313349551,https://capecod.craigslist.org/cto/d/truro-200...,cape cod / islands,https://capecod.craigslist.org,7750,2002.0,chevrolet,express g3500,good,8 cylinders,...,NaN,NaN,yellow,https://images.craigslist.org/00N0N_2DylXD6eu8...,Chevy Express G3500 with custom Unicel body. V...,NaN,ma,41.998800,-70.056400,2021-04-27T11:51:47-0400
92268,7314848176,https://daytona.craigslist.org/ctd/d/daytona-b...,daytona beach,https://daytona.craigslist.org,33990,2017.0,ford,mustang gt coupe 2d,good,8 cylinders,...,NaN,coupe,black,https://images.craigslist.org/00u0u_dNewfSc8VF...,Carvana is the safer way to buy a car During t...,NaN,fl,29.190000,-81.050000,2021-04-30T12:11:19-0400
206244,7307682792,https://lansing.craigslist.org/ctd/d/howell-20...,lansing,https://lansing.craigslist.org,36000,2014.0,chevrolet,silverado 3500hd,excellent,NaN,...,NaN,NaN,white,https://images.craigslist.org/00707_kJXwmYS9YW...,2014 Chevrolet Silverado 3500HD. 4x4. Single r...,NaN,mi,42.615900,-83.924800,2021-04-16T10:26:07-0400
40654,7305606578,https://monterey.craigslist.org/ctd/d/monterey...,monterey bay,https://monterey.craigslist.org,12590,2016.0,chevrolet,spark ev 1lt hatchback,good,NaN,...,NaN,hatchback,silver,https://images.craigslist.org/00b0b_5CPSPpGRxf...,Carvana is the safer way to buy a car During t...,NaN,ca,36.600000,-121.880000,2021-04-12T07:41:33-0700
8838,7311065377,https://flagstaff.craigslist.org/ctd/d/flagsta...,flagstaff / sedona,https://flagstaff.craigslist.org,33735,2019.0,cadillac,xt4 premium luxury,good,NaN,...,NaN,other,red,https://images.craigslist.org/00e0e_4cCwnT0aNK...,Why Buy From Flagstaff Chevrolet?Welcome to Fl...,NaN,az,35.189958,-111.666438,2021-04-22T14:20:50-0700
198214,7313993895,https://detroit.craigslist.org/okl/ctd/d/south...,detroit metro,https://detroit.craigslist.org,427,2018.0,ram,1500 express,good,NaN,...,NaN,pickup,black,https://images.craigslist.org/00e0e_kFj9Wxi6ro...,Why Buy From Southfield Chrysler Dodge Jeep Ra...,NaN,mi,42.494961,-83.283211,2021-04-28T15:40:35-0400
250007,7314643474,https://cnj.craigslist.org/ctd/d/east-brunswic...,central NJ,https://cnj.craigslist.org,5999,2006.0,acura,tl,excellent,6 cylinders,...,mid-size,sedan,grey,https://images.craigslist.org/00f0f_8CYYoDrsSF...,Up for sale is a 2006 Acura TL with 158K miles...,NaN,nj,40.428400,-74.406400,2021-04-29T21:50:16-0400
19679,7313265706,https://littlerock.craigslist.org/ctd/d/sherwo...,little rock,https://littlerock.craigslist.org,0,2014.0,ford,e250 cargo van,like new,8 cylinders,...,NaN,NaN,white,https://images.craigslist.org/00b0b_1f8M8HJyJZ...,"POWER LIFT, AUTOMATIC, POWER WINDOWS-LOCKS-MIR...",NaN,ar,34.867736,-92.196836,2021-04-27T08:14:39-0500
254891,7313155696,https://newjersey.craigslist.org/cto/d/cherry-...,north jersey,https://newjersey.craigslist.org,8795,2011.0,honda,accord,good,4 cylinders,...,NaN,NaN,grey,https://images.craigslist.org/01515_860Hgy5pDM...,"2011 Honda Accord EX-L with only 113,000 miles...",NaN,nj,39.930800,-75.017500,2021-04-26T21:43:15-0400
513,7313779658,https://bham.craigslist.org/ctd/d/fort-ogletho...,birmingham,https://bham.craigslist.org,27995,2017.0,nissan,nv2500 hd cargo,NaN,NaN,...,NaN,NaN,white,https://images.craigslist.org/00y0y_6rRrI2AjSQ...,** 2017 NISSAN NV 2500 HD CARGO VAN * UTILITY ...,NaN,al,34.950600,-85.243200,2021-04-28T08:39:37-0500
213988,7316768881,https://minneapolis.craigslist.org/ank/ctd/d/m...,minneapolis / st paul,https://minneapolis.craigslist.org,28963,2018.0,bmw,330i,NaN,NaN,...,full-size,sedan,NaN,https://images.craigslist.org/00M0M_ldPwCPJTV5...,2018 BMW 3-Series Gran Turismo 330i xDrive Lux...,NaN,mn,45.136043,-93.223214,2021-05-04T11:21:13-0500
386062,7311451792,https://saltlakecity.craigslist.org/ctd/d/wich...,salt lake city,https://saltlakecity.craigslist.org,0,NaN,NaN,nna,excellent,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00909_b0FBSW4Vi9...,0000 *** - Sienna *** Best Prices Mobility...,NaN,ut,37.679473,-97.335938,2021-04-23T11:45:19-0600
279287,7309495937,https://rochester.craigslist.org/cto/d/rochest...,rochester,https://rochester.craigslist.org,10490,2011.0,audi,a6,like new,6 cylinders,...,mid-size,sedan,grey,https://images.craigslist.org/00u0u_6xopNDYVCR...,Selling the cleanest Audi A6 in Rochester! (CL...,NaN,ny,43.234600,-77.657700,2021-04-19T17:18:25-0400
48801,7315990407,https://reno.craigslist.org/ctd/d/sacramento-2...,reno / tahoe,https://reno.craigslist.org,17991,2010.0,nissan,370z,NaN,NaN,...,NaN,coupe,black,https://images.craigslist.org/00V0V_k4j88rZpdI...,2010 Nissan 370Z Coupe 2D Offered by: Auto...,NaN,ca,38.597771,-121.403061,2021-05-02T16:30:03-0700
19119,7301611265,https://jonesboro.craigslist.org/ctd/d/jonesbo...,jonesboro,https://jonesboro.craigslist.org,38990,2020.0,audi,q5 45 tfsi premium plus,good,NaN,...,NaN,SUV,white,https://images.craigslist.org/00202_fjVrhHVsxL...,Carvana is the safer way to buy a car During t...,NaN,ar,35.820000,-90.680000,2021-04-04T07:32:44-0500
507,7313780759,https://bham.craigslist.org/ctd/d/fort-ogletho...,birmingham,https://bham.craigslist.org,31995,2012.0,ford,f350 super duty,NaN,NaN,...,NaN,NaN,white,https://images.craigslist.org/00101_4S44i2xCH4...,** 2012 FORD F350 XL SUPER DUTY * FLATBED * DU...,NaN,al,34.950600,-85.243200,2021-04-28T08:41:59-0500
229676,7303381856,https://missoula.craigslist.org/ctd/d/lolo-201...,missoula,https://missoula.craigslist.org,22295,2013.0,ford,f150,excellent,6 cylinders,...,NaN,pickup,NaN,https://images.craigslist.org/00505_4l5tatHMCV...,"Super clean, ONE OWNER Ford F150. This truck c...",NaN,mt,46.705688,-114.437259,2021-04-07T16:21:52-0600
129830,7314199452,https://honolulu.craigslist.org/big/cto/d/kail...,hawaii,https://honolulu.craigslist.org,200,2021.0,ram,1500 crew cab,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00a0a_8RPpdk9zp7...,"Aloha, We have a 2021 Dodge Ram Classic Trade...",NaN,hi,19.657962,-155.998306,2021-04-28T19:00:00-1000
291349,7307885980,https://cincinnati.craigslist.org/ctd/d/newpor...,cincinnati,https://cincinnati.craigslist.org,8495,2013.0,hyundai,sonata,NaN,NaN,...,full-size,sedan,silver,https://images.craigslist.org/00k0k_kA5yu0P7oA...,2013 Hyundai Sonata GLS Offered by: HAND-P...,NaN,oh,39.002570,-84.423424,2021-04-16T15:31:40-0400
170708,7303599717,https://bgky.craigslist.org/ctd/d/goodlettsvil...,bowling green,https://bgky.craigslist.org,14800,2018.0,kia,soul,excellent,NaN,...,NaN,SUV,grey,https://images.craigslist.org/00k0k_c30vHsJYOY...,Call ☏ (615) 992−3147 First Class Auto Sales ...,NaN,ky,36.292259,-86.733337,2021-04-08T09:00:13-0500
32149,7314340066,https://inlandempire.craigslist.org/ctd/d/more...,inland empire,https://inlandempire.craigslist.org,399,2018.0,jeep,wrangler jk unlimited sport,NaN,NaN,...,NaN,SUV,white,https://images.craigslist.org/01515_c8gT1a2k1d...,2018 Jeep Wrangler JK Unlimited Sport S SUV201...,NaN,ca,34.023568,-117.111767,2021-04-29T08:48:40-0700
216143,7315271346,https://minneapolis.craigslist.org/ank/ctd/d/m...,minneapolis / st paul,https://minneapolis.craigslist.org,159,2002.0,ford,ranger xlt,excellent,6 cylinders,...,compact,truck,silver,https://images.craigslist.org/00a0a_hV8tmGcYVl...,WE WILL FINANCE THIS AT $159 PER MO SO CALL...,NaN,mn,45.169700,-93.188900,2021-05-01T09:12:35-0500
27444,7311463128,https://fresno.craigslist.org/ctd/d/fresno-201...,fresno / madera,https://fresno.craigslist.org,28999,2014.0,chevrolet,silverado 1500,NaN,8 cylinders,...,NaN,truck,white,https://images.craigslist.org/00000_9aOCu0XjBu...,2014 Chevrolet Silverado 1500 LTZ Pickup 4D 5 ...,NaN,ca,36.774617,-119.791164,2021-04-23T11:02:55-0700
179224,7311912493,https://maine.craigslist.org/ctd/d/plaistow-20...,maine,https://maine.craigslist.org,38995,2015.0,ford,super duty f-350 srw,excellent,8 cylinders,...,full-size,truck,green,https://images.craigslist.org/00Z0Z_hlov1b3Zd3...,2015 Ford Super Duty F-350 SRW LARIAT SUPERCAB...,NaN,me,42.838576,-71.106880,2021-04-24T12:36:05-0400
97255,7309753018,https://gainesville.craigslist.org/ctd/d/gaine...,gainesville,https://gainesville.craigslist.org,700,2013.0,nissan,altima,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00H0H_1VaTq8Ll22...,CREDIT CARS- $700.00 DOWN- RIGHT ON THE CORNER...,NaN,fl,29.770834,-82.283186,2021-04-20T09:36:47-0400
285542,7311247435,https://nh.craigslist.org/ctd/d/east-windsor-c...,new hampshire,https://nh.craigslist.org,9995,2007.0,cadillac,escalade,excellent,8 cylinders,...,full-size,SUV,white,https://images.craigslist.org/00000_kqVE1ZlpHO...,2007 CADILLAC ESCALADE2007 Cadillac Escalade L...,NaN,nh,41.909900,-72.602900,2021-04-23T06:21:51-0400
303287,7310932613,https://youngstown.craigslist.org/ctd/d/2013-t...,youngstown,https://youngstown.craigslist.org,10995,2013.0,toyota,sienna,excellent,NaN,...,NaN,mini-van,silver,https://images.craigslist.org/00g0g_iNUiMPegLQ...,"The most reliable van you money can buy, Price...",NaN,oh,NaN,NaN,2021-04-22T13:34:16-0400
294445,7304730166,https://cleveland.craigslist.org/ctd/d/rocky-r...,cleveland,https://cleveland.craigslist.org,7995,2014.0,volkswagen,jetta,NaN,4 cylinders,...,compact,sedan,custom,https://images.craigslist.org/00707_2biUtlCXNS...,SOLD!!! This Volkswagen Jetta has just been ...,NaN,oh,41.456783,-81.883689,2021-04-10T12:40:22-0400
198312,7313907621,https://detroit.craigslist.org/mcb/ctd/d/rosev...,detroit metro,https://detroit.craigslist.org,1999,2003.0,dodge,neon,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00i0i_6R05VL2ArL...,2.0L 4CYL sport this is a local trade out of l...,NaN,mi,42.503400,-82.938700,2021-04-28T13:17:32-0400
380534,7315470643,https://sanantonio.craigslist.org/ctd/d/san-an...,san antonio,https://sanantonio.craigslist.org,13500,2012.0,ford,f-250 super duty,like new,8 cylinders,...,full-size,pickup,white,https://images.craigslist.org/00R0R_dI9yB9yz1Z...,"IN GREAT INTERIOR , EXTERIOR , MECHANICAL COND...",NaN,tx,29.563552,-98.420182,2021-05-01T14:57:34-0500
154821,7309508001,https://southbend.craigslist.org/ctd/d/warsaw-...,south bend / michiana,https://southbend.craigslist.org,7395,2006.0,ford,escape xlt,excellent,6 cylinders,...,mid-size,SUV,green,https://images.craigslist.org/00N0N_45i9BRZy90...,"2006 Ford Escape XLT ONLY 74,264 Miles! 4WD/AW...",NaN,in,41.235432,-85.840501,2021-04-19T17:39:29-0400
136530,7316029694,https://spokane.craigslist.org/cto/d/spokane-2...,spokane / coeur d'alene,https://spokane.craigslist.org,3000,2000.0,volkswagen,jetta gl,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00T0T_lngACYyu4T...,"2000 VW Jetta 2.0 5-Speed. 196,500 Miles. $300...",NaN,id,47.646126,-117.240189,2021-05-02T18:23:28-0700
250919,7311113944,https://cnj.craigslist.org/cto/d/lakewood-grea...,central NJ,https://cnj.craigslist.org,4000,2011.0,mazda,cx-9,like new,NaN,...,NaN,SUV,black,https://images.craigslist.org/00e0e_jXTmIajgc7...,Ive got a beautiful Mazda. Its in great condit...,NaN,nj,40.085000,-74.204200,2021-04-22T19:03:19-0400
66434,7305638874,https://stockton.craigslist.org/ctd/d/san-rafa...,stockton,https://stockton.craigslist.org,15488,2009.0,jaguar,xk series,excellent,8 cylinders,...,NaN,coupe,NaN,https://images.craigslist.org/00X0X_bKmDrbBU1J...,"2009 Jaguar XK Series FOR ONLY $225/mo!81,648...",NaN,ca,37.963201,-122.509472,2021-04-12T08:31:45-0700
69171,7316264354,https://visalia.craigslist.org/ctd/d/visalia-2...,visalia-tulare,https://visalia.craigslist.org,23590,2018.0,infiniti,q50 2.0t pure sedan 4d,good,NaN,...,NaN,sedan,NaN,https://images.craigslist.org/01414_d8mNTfjOqc...,Carvana is the safer way to buy a car During t...,NaN,ca,36.400000,-119.380000,2021-05-03T09:41:07-0700
303901,7305618848,https://zanesville.craigslist.org/ctd/d/columb...,zanesville / cambridge,https://zanesville.craigslist.org,10981,2018.0,chevrolet,malibu lt,excellent,4 cylinders,...,NaN,sedan,NaN,https://images.craigslist.org/00000_9o3wMDz1QI...,$164/mo - 2018 Chevrolet MALIBU LT - Easy Fina...,NaN,oh,39.884989,-82.967588,2021-04-12T11:01:34-0400
105215,7314960808,https://orlando.craigslist.org/ctd/d/orlando-2...,orlando,https://orlando.craigslist.org,32999,2020.0,acura,tlx,excellent,6 cylinders,...,NaN,sedan,grey,https://images.craigslist.org/00V0V_bmNpM9vxT4...,CREDIT AMNESTY! SE HABLA ESPANOL !!OPEN SUNDA...,NaN,fl,28.466088,-81.396429,2021-04-30T15:14:10-0400
173508,7306915201,https://louisville.craigslist.org/ctd/d/south-...,louisville,https://louisville.craigslist.org,47990,2014.0,ford,super duty f-550 drw,good,8 cylinders,...,full-size,truck,white,https://images.craigslist.org/00O0O_hG27Ddbvfc...,2014 Ford Super Duty F-550 DRW 11 FOOT DUMP TR...,NaN,ky,40.468785,-74.281707,2021-04-14T17:45:57-0400
264078,7313499730,https://albany.craigslist.org/ctd/d/albany-201...,albany,https://albany.craigslist.org,39590,2019.0,honda,civic type r touring,good,NaN,...,NaN,sedan,NaN,https://images.craigslist.org/01111_ingAyPf5hR...,Carvana is the safer way to buy a car During t...,NaN,ny,42.660000,-73.790000,2021-04-27T15:51:02-0400
3443,7306741799,https://huntsville.craigslist.org/ctd/d/decatu...,huntsville / decatur,https://huntsville.craigslist.org,25590,2018.0,mitsubishi,outlander phev sel,good,NaN,...,NaN,other,black,https://images.craigslist.org/00a0a_d0I7tFj4n6...,Carvana is the safer way to buy a car During t...,NaN,al,34.570000,-86.980000,2021-04-14T12:01:20-0500
139819,7306881138,https://chambana.craigslist.org/cto/d/urbana-2...,champaign urbana,https://chambana.craigslist.org,3000,2006.0,jeep,commander limited,fair,8 cylinders,...,NaN,NaN,green,https://images.craigslist.org/01010_358req7lAg...,Selling a 2006 Jeep Commander Limited. Almost...,NaN,il,40.109500,-88.203600,2021-04-14T15:44:59-0500
419966,7315324571,https://madison.craigslist.org/ctd/d/madison-2...,madison,https://madison.craigslist.org,26990,2019.0,volkswagen,jetta gli 35th,good,NaN,...,NaN,sedan,NaN,https://images.craigslist.org/00F0F_eKxbnA4SWg...,Carvana is the safer way to buy a car During t...,NaN,wi,43.070000,-89.380000,2021-05-01T10:51:17-0500
785,7311389428,https://bham.craigslist.org/ctd/d/dolomite-200...,birmingham,https://bham.craigslist.org,4500,2005.0,acura,mdx,NaN,6 cylinders,...,NaN,SUV,blue,https://images.craigslist.org/00j0j_cZuw30dPly...,2005 *Acura* *MDX* 4dr SUV Automatic Touring R...,NaN,al,33.455361,-86.962474,2021-04-23T11:11:25-0500
368364,7303746918,https://corpuschristi.craigslist.org/ctd/d/cor...,corpus christi,https://corpuschristi.craigslist.org,24590,2018.0,lincoln,mkz select sedan 4d,good,NaN,...,NaN,sedan,white,https://images.craigslist.org/00R0R_iuWMpodqwt...,Carvana is the safer way to buy a car During t...,NaN,tx,27.800000,-97.390000,2021-04-08T12:51:01-0500
224625,7307468407,https://billings.craigslist.org/ctd/d/billings...,billings,https://billings.craigslist.org,17290,2010.0,chevrolet,avalanche ltz,excellent,8 cylinders,...,full-size,SUV,blue,https://images.craigslist.org/00u0u_kbOVZMOSi3...,2010 Chevrolet Avalanche LTZ 4WD - Leather/Moo...,NaN,mt,45.769572,-108.527072,2021-04-15T17:06:11-0600
101418,7308378858,https://lakeland.craigslist.org/ctd/d/orlando-...,lakeland,https://lakeland.craigslist.org,23999,2018.0,chrysler,300,excellent,NaN,...,NaN,sedan,black,https://images.craigslist.org/00505_5Ntkw32yey...,CREDIT AMNESTY! SE HABLA ESPANOL !!OPEN SUNDA...,NaN,fl,28.466088,-81.396429,2021-04-17T14:30:31-0400
376416,7314821239,https://houston.craigslist.org/ctd/d/south-hou...,houston,https://houston.craigslist.org,2000,2011.0,hyundai,sonata,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00E0E_aTCSD2Ivyt...,"2,000 DOWN NO CREDIT NEEDED EVERYONES APPROVED...",NaN,tx,29.660100,-95.225800,2021-04-30T10:27:44-0500
233440,7311536903,https://charlotte.craigslist.org/ctd/d/greensb...,charlotte,https://charlotte.craigslist.org,23698,2013.0,ford,f-150,NaN,NaN,...,NaN,NaN,NaN,https://images.craigslist.org/00r0r_3CdsUGO03D...,"2013 Ford F-150 4WD SuperCrew 145"" Lariat Oak...",NaN,nc,36.129540,-79.957520,2021-04-23T16:01:58-0400
206606,7302776988,https://lansing.craigslist.org/ctd/d/lansing-2...,lansing,https://lansing.craigslist.org,23590,2017.0,infiniti,qx50 sport utility 4d,good,6 cylinders,...,NaN,hatchback,silver,https://images.craigslist.org/00B0B_2wzJz6CGFP...,Carvana is the safer way to buy a car During t...,NaN,mi,42.700000,-84.550000,2021-04-06T15:51:01-0400
255243,7311982694,https://newjersey.craigslist.org/cto/d/totowa-...,north jersey,https://newjersey.craigslist.org,9500,2011.0,jeep,liberty,good,NaN,...,NaN,SUV,silver,https://images.craigslist.org/00i0i_iKB2tyQLoO...,"2011 Jeep Liberty Milage 101,000. Asking $9,50...",NaN,nj,40.914300,-74.167100,2021-04-24T14:24:52-0400

    3.What is the data_type of columns ?

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 26 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  object
 2   region        426880 non-null  object
 3   region_url    426880 non-null  object
 4   price         426880 non-null  int64
 5   year          425675 non-null  float64
 6   manufacturer  409234 non-null  object
 7   model         421603 non-null  object
 8   condition     252776 non-null  object
 9   cylinders     249202 non-null  object
 10  fuel          423867 non-null  object
 11  odometer      422480 non-null  float64
 12  title_status  418638 non-null  object
 13  transmission  424324 non-null  object
 14  VIN           265838 non-null  object
 15  drive         296313 non-null  object
 16  size          120519 non-null  object
 17  type          334022 non-null  object
 18  paint_color   296677 non-null  object
 19  image_url     426812 non-null  object
 20  description   426810 non-null  object
 21  county        0 non-null       float64
 22  state         426880 non-null  object
 23  lat           420331 non-null  float64
 24  long          420331 non-null  float64
 25  posting_date  426812 non-null  object
dtypes: float64(5), int64(2), object(19)
memory usage: 84.7+ MB

    4.Are there any missing values of the columns ?

In [8]:
missing_values = df.isnull().sum().sort_values(ascending=False)
missing_percentage = (missing_values/len(df))*100

missing_df = pd.DataFrame({'Missing_counts':missing_values,'Perecentage':missing_percentage})
print(missing_df)

              Missing_counts  Perecentage
county                426880   100.000000
size                  306361    71.767476
cylinders             177678    41.622470
condition             174104    40.785232
VIN                   161042    37.725356
drive                 130567    30.586347
paint_color           130203    30.501078
type                   92858    21.752717
manufacturer           17646     4.133714
title_status            8242     1.930753
lat                     6549     1.534155
long                    6549     1.534155
model                   5277     1.236179
odometer                4400     1.030735
fuel                    3013     0.705819
transmission            2556     0.598763
year                    1205     0.282281
description               70     0.016398
posting_date              68     0.015930
image_url                 68     0.015930
region_url                 0     0.000000
url                        0     0.000000
id                         0     0.000000
region                     0     0.000000
price                      0     0.000000
state                      0     0.000000

    5.How does the data look mathematically ?

In [9]:
df.describe()

,id,price,year,odometer,county,lat,long
count,4.268800e+05,4.268800e+05,425675.000000,4.224800e+05,0.0,420331.000000,420331.000000
mean,7.311487e+09,7.519903e+04,2011.235191,9.804333e+04,NaN,38.493940,-94.748599
std,4.473170e+06,1.218228e+07,9.452120,2.138815e+05,NaN,5.841533,18.365462
min,7.207408e+09,0.000000e+00,1900.000000,0.000000e+00,NaN,-84.122245,-159.827728
25%,7.308143e+09,5.900000e+03,2008.000000,3.770400e+04,NaN,34.601900,-111.939847
50%,7.312621e+09,1.395000e+04,2013.000000,8.554800e+04,NaN,39.150100,-88.432600
75%,7.315254e+09,2.648575e+04,2017.000000,1.335425e+05,NaN,42.398900,-80.832039
max,7.317101e+09,3.736929e+09,2022.000000,1.000000e+07,NaN,82.390818,173.885502

    6.Are there duplicates values ?

In [10]:
df.duplicated().sum()

0

    7.Are there any Relation between cols ?

In [11]:
# df.corr() for numerical columns only we will that later in visalization

    8.Are there any max dataTypes

### Observation from Basic Questions
        1.county has 100% missing values
        2.size has 71%  missing values
        3.cylinder and condition has 41% and 40% missing data
        4.There zero duplicated values
        5.Car sold it zero price which is dont makes sense
        6.odometer has zero mileage which dont makes sense of use car
        7.Year has float data type which should be int
        8.posting Year columns is object data type which should be data_time data type
        9.Cylinder columns has max data type eg: 4 cylindr
        10.Model columns has also max data type

## 2.Cleaning Data

    1.droping columns 
        following are the columns
        a.county bcuz 100% missing values
        b.region url bucz region columns present so don't need to region url

In [12]:
drop_columns=['county','region_url']
df = df.drop(columns=drop_columns)

    2.Handling Missing values

In [13]:
##Handling size columns
df['size'].unique()
df['size']=df['size'].fillna(df['size'].mode()[0])

In [14]:
## Handling Cylinder columns
##first it should remove from mix datatypes to int
df['cylinders'] = df['cylinders'].str.extract(r'(\d+)')

## Second handling missing values
df['cylinders'] = df['cylinders'].fillna(df['cylinders'].mode()[0])

In [15]:
## Handling missing value of  all categorical cols with mode
categorical_cols = df.select_dtypes(include=['object']).columns
categorical_cols

for col in categorical_cols:
    df[col]=df[col].fillna(df[col].mode()[0])

In [16]:
numerical_cols = df.select_dtypes(include=['number']).columns

for col in numerical_cols:
    df[col]=df[col].fillna(df[col].mean())

In [17]:
df['posting_date'] = pd.to_datetime(df['posting_date'],utc=True)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426880 entries, 0 to 426879
Data columns (total 24 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            426880 non-null  int64
 1   url           426880 non-null  object
 2   region        426880 non-null  object
 3   price         426880 non-null  int64
 4   year          426880 non-null  float64
 5   manufacturer  426880 non-null  object
 6   model         426880 non-null  object
 7   condition     426880 non-null  object
 8   cylinders     426880 non-null  object
 9   fuel          426880 non-null  object
 10  odometer      426880 non-null  float64
 11  title_status  426880 non-null  object
 12  transmission  426880 non-null  object
 13  VIN           426880 non-null  object
 14  drive         426880 non-null  object
 15  size          426880 non-null  object
 16  type          426880 non-null  object
 17  paint_color   426880 non-null  object
 18  image_url     426880 non-null  object
 19  description   426880 non-null  object
 20  state         426880 non-null  object
 21  lat           426880 non-null  float64
 22  long          426880 non-null  float64
 23  posting_date  426880 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), float64(4), int64(2), object(17)
memory usage: 78.2+ MB

## 2.EDA

In [19]:
#Numerical columns
print(numerical_cols)
#Categorical columns
print(categorical_cols)

Index(['id', 'price', 'year', 'odometer', 'lat', 'long'], dtype='object')
Index(['url', 'region', 'manufacturer', 'model', 'condition', 'cylinders',
       'fuel', 'title_status', 'transmission', 'VIN', 'drive', 'size', 'type',
       'paint_color', 'image_url', 'description', 'state', 'posting_date'],
      dtype='object')

### 1.Univaraite

    a.Numerical

        i.Price cols

In [ ]:
sns.displot(df['price'])

    b.Categorical

### 2.Bivaraite and Multivaraite

    a.Numerical - Numerical

    b.Categorical - Numerical

    c.Categorical - Categorical